'use client'
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from '../components/NavBar'
import { CartContext } from "../context/CartContext";
import Footer from '../components/Footer'

import {
  ClerkProvider,

} from '@clerk/nextjs'
import { useState } from "react";
import { usePathname } from "next/navigation";


const inter = Roboto({ subsets: ["latin"],weight:"700" });



/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);

  return (
  <ClerkProvider>
    <CartContext.Provider value={{cart,setCart}}>
      <html lang="en">
        <body className={inter.className}>
          <NavBar/>
          {children}
          <Footer/>
        </body>
      </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
